### ISSUE TITLE
linking issue

### ISSUE THREAD

**Issue by journeytosilius** [chungphb/basic-grpc#1]
Hi, since I have protobuff installed on my system, I have included the .local installation with the latest version, and includes work but I have a linking problem and I believe it's because these vars : 

```
        ${_PROTOBUF_LIBPROTOBUF}
        ${_REFLECTION}
        ${_GRPC_GRPCPP})
```

are pointing to the protobuff system installation. what are these libs named exactly so I can point the .a lib file directly instead of these vars ? 

Thanks

**Comment by chungphb** [comment]
@chromafunk 
`${_PROTOBUF_LIBPROTOBUF}` is `protobuf::libprotobuf`.
`${_REFLECTION}` is `gRPC::grpc++_reflection`.
`${_GRPC_GRPCPP}` is `gRPC::grpc++`.

**Comment by journeytosilius** [comment]
thank you
